"""
WhiteHatHacker AI — Intelligence Engine

The core "brain" integration layer that transforms the bot from a scanner
into an autonomous bug bounty hunter. This module provides high-level
intelligence functions that are called at every pipeline stage to make
LLM-driven decisions.

Key Capabilities:
  1. Strategic Attack Planning — analyze recon data, create targeted plans
  2. Dynamic Tool Configuration — LLM picks tools & options per context
  3. Output Analysis — LLM reads tool output to identify subtle vulns
  4. Evidence Verification — LLM confirms exploitability from HTTP data
  5. Custom Template Generation — write nuclei YAML for target-specific checks
  6. Exploit/PoC Generation — write Python/curl PoCs for confirmed vulns
  7. Report Enrichment — professional narrative + impact analysis
"""

from __future__ import annotations

import asyncio
import json
import hashlib
import time
import re
from collections import OrderedDict
from typing import Any

from loguru import logger
from pydantic import BaseModel, Field

from src.brain.engine import BrainEngine, BrainType, BrainResponse
from src.brain.router import BrainRouter

# ── Prompt Credential Sanitization ────────────────────────────────
# Matches key=value or key: value patterns for sensitive fields.
# Applied before any content is sent to the LLM brain to prevent
# accidental credential leakage through recon data, OSINT results,
# or tool output that may contain discovered secrets.
_PROMPT_SENSITIVE_PATTERNS: tuple[str, ...] = (
    "api_key", "api_token", "apikey", "secret_key", "client_secret",
    "password", "credential", "bearer", "cookie",
    "jwt", "private_key", "access_key",
    "refresh_token", "authorization", "auth_token", "auth_key",
    "aws_secret", "aws_access", "slack_token", "github_token",
    "database_url", "db_password", "mysql_pwd", "postgres_password",
)
_PROMPT_SENSITIVE_RE = re.compile(
    r'\b(' + '|'.join(re.escape(p) for p in _PROMPT_SENSITIVE_PATTERNS) + r')\s*[=:]\s*\S+',
    re.IGNORECASE,
)


def _sanitize_prompt(text: str) -> str:
    """Redact credential-like patterns from text before sending to LLM."""
    if not text:
        return text
    return _PROMPT_SENSITIVE_RE.sub(r'\1=***REDACTED***', text)


# ── Data Models ───────────────────────────────────────────────────

class AttackVector(BaseModel):
    """A single attack vector identified by the LLM."""
    endpoint: str = ""
    parameter: str = ""
    vuln_type: str = ""         # sqli, xss, ssrf, idor, etc.
    priority: str = "medium"    # critical, high, medium, low
    reasoning: str = ""
    tools: list[str] = Field(default_factory=list)
    payloads: list[str] = Field(default_factory=list)
    estimated_time: int = 60


class IntelligencePlan(BaseModel):
    """LLM-generated strategic attack plan."""
    target: str = ""
    summary: str = ""
    attack_vectors: list[AttackVector] = Field(default_factory=list)
    custom_templates_needed: list[dict] = Field(default_factory=list)
    high_value_endpoints: list[str] = Field(default_factory=list)
    technologies_of_interest: list[str] = Field(default_factory=list)
    waf_bypass_strategies: list[str] = Field(default_factory=list)


class VerificationResult(BaseModel):
    """LLM verification of a vulnerability finding."""
    is_real: bool = False
    confidence: float = 0.0  # Bug 5.2l-5: was 50.0 — 'no opinion' should be 0, not 50%
    reasoning: str = ""
    additional_evidence: str = ""
    suggested_poc_steps: list[str] = Field(default_factory=list)
    exploit_feasibility: str = "unknown"  # trivial, moderate, complex, unlikely
    cvss_override: float | None = None


class NucleiTemplate(BaseModel):
    """A custom nuclei template generated by LLM."""
    template_id: str = ""
    name: str = ""
    severity: str = "medium"
    description: str = ""
    yaml_content: str = ""
    target_tech: str = ""


class PoCScript(BaseModel):
    """A Proof of Concept script generated by LLM."""
    language: str = "python"
    script_content: str = ""
    curl_command: str = ""
    browser_steps: list[str] = Field(default_factory=list)
    expected_output: str = ""
    dependencies: list[str] = Field(default_factory=list)


class NextActionDecision(BaseModel):
    """LLM-guided next-action recommendation inside an existing stage."""
    action: str = "continue"
    reason: str = ""
    next_tool: str = ""
    skip_tools: list[str] = Field(default_factory=list)
    deep_dive_target: str = ""
    deep_dive_tool: str = ""       # P3-2: specific tool for deep_dive action
    change_strategy: str = ""      # P3-2: new scan profile (stealth/balanced/aggressive)
    retry_with_auth: bool = False  # P3-2: re-run tool with auth headers
    request_oob_check: bool = False  # P3-2: check interactsh OOB callbacks
    stage_transition: str = ""
    priority_findings: list[str] = Field(default_factory=list)
    time_estimate: str = ""


# ── Intelligence Engine ───────────────────────────────────────────

class IntelligenceEngine:
    """
    High-level intelligence layer that wraps BrainEngine calls
    with security-domain-specific prompts and structured output parsing.

    This is the primary interface between the scanning pipeline and the LLM.
    """

    def __init__(self, brain_engine: BrainEngine, router: BrainRouter | None = None):
        self.brain = brain_engine
        self.router = router
        self._call_count = 0
        self._total_time = 0.0
        self._consecutive_failures = 0
        # B2: Central brain-down flag — set after N consecutive failures
        self._brain_down = False
        self._brain_down_threshold = 3  # Mark down after 3 consecutive failures
        self._brain_down_time: float = 0.0  # When brain was marked down
        self._brain_down_recovery_secs: float = 300.0  # Auto-retry after 5 minutes
        # E1: Simple hash-based response cache for expensive brain calls
        self._cache: OrderedDict[str, tuple[str, float]] = OrderedDict()
        self._cache_hits = 0
        self._cache_max_size = 200  # Evict LRU when exceeded
        self._cache_ttl = 600.0     # Cache entries expire after 10 minutes
        self._cache_lock = asyncio.Lock()  # Protect OrderedDict from concurrent access

        # A3: Brain response quality metrics (V16)
        self._json_parse_ok = 0       # _brain_call_json → first-try parse success
        self._json_parse_retry_ok = 0 # _brain_call_json → retry parse success
        self._json_parse_fail = 0     # _brain_call_json → total failure (both attempts)
        self._brain_call_success = 0  # _brain_call → non-empty response
        self._brain_call_empty = 0    # _brain_call → empty response
        self._brain_call_error = 0    # _brain_call → exception

    def get_brain_metrics(self) -> dict[str, int | float]:
        """Return brain call quality metrics for benchmarking."""
        total_json = self._json_parse_ok + self._json_parse_retry_ok + self._json_parse_fail
        total_calls = self._brain_call_success + self._brain_call_empty + self._brain_call_error
        return {
            "total_calls": self._call_count,
            "total_time_s": round(self._total_time, 1),
            "cache_hits": self._cache_hits,
            "json_parse_first_try": self._json_parse_ok,
            "json_parse_retry": self._json_parse_retry_ok,
            "json_parse_fail": self._json_parse_fail,
            "json_success_rate": round(
                (self._json_parse_ok + self._json_parse_retry_ok) / total_json * 100, 1
            ) if total_json > 0 else 100.0,
            "call_success": self._brain_call_success,
            "call_empty": self._brain_call_empty,
            "call_error": self._brain_call_error,
            "call_success_rate": round(
                self._brain_call_success / total_calls * 100, 1
            ) if total_calls > 0 else 100.0,
        }

    @property
    def is_available(self) -> bool:
        if self._brain_down:
            # Auto-recover after _brain_down_recovery_secs
            if self._brain_down_time > 0 and (time.time() - self._brain_down_time) >= self._brain_down_recovery_secs:
                logger.info(
                    f"Brain auto-recovery: {self._brain_down_recovery_secs:.0f}s elapsed since brain-down. "
                    f"Resetting brain-down flag to allow retry."
                )
                self._brain_down = False
                self._consecutive_failures = 0
                self._brain_down_time = 0.0
                # Fall through to normal availability check below
            else:
                return False
        return self.brain is not None and (
            self.brain.has_primary or self.brain.has_secondary
        )

    # ── 1. Strategic Attack Planning ──────────────────────────────

    # ── P3-4 helpers: recon data summarization ──────────────────

    @staticmethod
    def _cluster_urls(urls: list[str], max_clusters: int = 30) -> dict[str, list[str]]:
        """Group URLs by path pattern, replacing dynamic segments with {id}.

        Returns mapping from pattern → representative URLs (max 3 each).
        E.g. "/api/v1/users/123" and "/api/v1/users/456" → "/api/v1/users/{id}" → [both]
        """
        from urllib.parse import urlparse
        import re as _re

        clusters: dict[str, list[str]] = {}
        _DYNAMIC_SEG = _re.compile(
            r'/(?:'
            r'[0-9a-f]{8,}'         # hex ids / uuids
            r'|[0-9]+'             # numeric ids
            r'|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'  # full uuid
            r')(?=/|$)'
        )

        for u in urls:
            try:
                parsed = urlparse(u)
                pattern = _DYNAMIC_SEG.sub('/{id}', parsed.path)
                # Normalize trailing slash
                pattern = pattern.rstrip('/') or '/'
                if pattern not in clusters:
                    if len(clusters) >= max_clusters:
                        continue
                    clusters[pattern] = []
                if len(clusters[pattern]) < 3:
                    clusters[pattern].append(u)
            except Exception:
                continue
        return clusters

    @staticmethod
    def _compact_tech_stack(technologies: dict[str, list[str]]) -> dict[str, list[str]]:
        """Merge per-host tech lists into a single deduplicated summary.

        Returns {"frameworks": [...], "servers": [...], "languages": [...], "other": [...]}.
        """
        all_techs: set[str] = set()
        for techs in technologies.values():
            all_techs.update(techs)

        # Categorize by keyword heuristics
        frameworks: list[str] = []
        servers: list[str] = []
        languages: list[str] = []
        other: list[str] = []

        _fw_kw = {"react", "angular", "vue", "django", "flask", "laravel", "rails",
                   "spring boot", "express", "next.js", "nuxt", "wordpress", "drupal", "joomla",
                   "symfony", "fastapi", "jquery", "bootstrap"}
        _srv_kw = {"nginx", "apache", "iis", "tomcat", "caddy", "lighttpd", "envoy",
                    "haproxy", "cloudflare", "varnish", "litespeed", "openresty",
                    "gunicorn", "uwsgi", "puma", "unicorn"}
        _lang_kw = {"php", "python", "java", "ruby", "node.js", "golang", "rust", "perl",
                     "asp.net", "c#", ".net", "typescript", "javascript"}

        for t in sorted(all_techs):
            t_lower = t.lower()
            if any(kw in t_lower for kw in _fw_kw):
                frameworks.append(t)
            elif any(kw in t_lower for kw in _srv_kw):
                servers.append(t)
            elif any(kw in t_lower for kw in _lang_kw):
                languages.append(t)
            else:
                other.append(t)

        result: dict[str, list[str]] = {}
        if frameworks:
            result["frameworks"] = frameworks[:10]
        if servers:
            result["servers"] = servers[:5]
        if languages:
            result["languages"] = languages[:5]
        if other:
            result["other"] = other[:10]
        return result

    @staticmethod
    def _compact_ports(open_ports: dict[str, list[int]]) -> dict[str, list[int]]:
        """Deduplicate ports across hosts — keep unique port→host mapping."""
        all_ports: set[int] = set()
        for ports in open_ports.values():
            all_ports.update(ports)
        # Interesting non-standard ports first
        standard = {80, 443, 22, 21, 25, 53, 110, 143}
        interesting = sorted(p for p in all_ports if p not in standard)[:20]
        std_present = sorted(p for p in all_ports if p in standard)
        return {
            "standard": std_present,
            "non_standard": interesting,
            "total_hosts": len(open_ports),
        }

    async def analyze_recon_and_plan(
        self,
        target: str,
        subdomains: list[str],
        live_hosts: list[str],
        technologies: dict[str, list[str]],  # host -> [tech, ...]
        open_ports: dict[str, list[int]],     # host -> [port, ...]
        dns_records: list[dict],
        urls: list[str],
        osint_data: dict[str, Any] | None = None,
    ) -> IntelligencePlan:
        """
        Analyze all recon data and produce a strategic attack plan.
        Called after passive+active recon, before enumeration.
        Uses Primary brain (32B) for deep strategic analysis.

        P3-4: Smart summarization — URL clustering, compact tech stack,
        token budget management (target ~8K tokens for prompt body).
        """
        if not self.is_available:
            return IntelligencePlan(target=target)

        # ── P3-4: Compact tech stack (merge all hosts) ──
        tech_compact = self._compact_tech_stack(technologies)

        # ── P3-4: Compact port summary ──
        port_compact = self._compact_ports(open_ports)

        # ── P3-4: URL clustering by path pattern ──
        url_clusters = self._cluster_urls(urls, max_clusters=30)
        # Format clusters compactly: pattern (count) → example
        url_lines: list[str] = []
        for pattern, examples in sorted(url_clusters.items(), key=lambda x: -len(x[1])):
            count = len([u for u in urls if pattern.replace('{id}', '') in u]) or len(examples)
            url_lines.append(f"  {pattern} ({count}x) → {examples[0]}")
        url_block = chr(10).join(url_lines[:40])

        # ── P3-4: Filter interesting subdomains ──
        boring_prefixes = ("www.", "mail.", "smtp.", "pop.", "imap.", "ns1.", "ns2.", "ns3.", "autodiscover.")
        interesting_subs = [s for s in subdomains if not s.startswith(boring_prefixes)][:20]
        if not interesting_subs:
            interesting_subs = subdomains[:20]

        # ── P3-4: Compact OSINT ──
        osint_str = json.dumps(osint_data or {}, indent=1, default=str)
        if len(osint_str) > 1500:
            osint_str = osint_str[:1500] + "\n  ... (truncated)"

        prompt = f"""## Task: Strategic Attack Planning

You are an elite bug bounty hunter analyzing reconnaissance data for {target}.
Create a prioritized attack plan identifying the most promising vulnerability vectors.

### Reconnaissance Summary

**Subdomains ({len(subdomains)} found, showing {len(interesting_subs)}):**
{chr(10).join(f'  - {s}' for s in interesting_subs)}

**Live Hosts ({len(live_hosts)} total, showing up to 10):**
{chr(10).join(f'  - {h}' for h in live_hosts[:10])}

**Technology Stack (merged across all hosts):**
{json.dumps(tech_compact, indent=1)}

**Open Ports (across {port_compact.get('total_hosts', 0)} hosts):**
  Standard: {port_compact.get('standard', [])}
  Non-standard: {port_compact.get('non_standard', [])}

**DNS Records ({len(dns_records)} total, showing {min(len(dns_records), 8)}):**
{json.dumps(dns_records[:8], indent=1, default=str)}

**URL Patterns ({len(urls)} total URLs, {len(url_clusters)} unique patterns):**
{url_block}

**OSINT Data:**
{osint_str}

### Analysis Requirements

1. Identify the TOP 10 most promising attack vectors with specific endpoints
2. For each vector, specify:
   - Exact endpoint/parameter to test
   - Vulnerability type (sqli, xss, ssrf, idor, auth_bypass, etc.)
   - Priority (critical/high/medium/low)
   - Which tools to use and with what options
   - Specific payloads or test strategies
   - Reasoning for why this is promising
3. Identify technologies that need CUSTOM nuclei templates
4. Identify high-value endpoints (admin, API, auth, file upload, etc.)
5. Suggest WAF bypass strategies if CDN/WAF detected
6. Prioritize vectors by: exploitability × impact × uniqueness

### Response Format (JSON)
{{
  "summary": "Overall assessment of target security posture",
  "attack_vectors": [
    {{
      "endpoint": "/api/v1/users?id=1",
      "parameter": "id",
      "vuln_type": "idor",
      "priority": "critical",
      "reasoning": "Predictable user IDs with no auth check observed",
      "tools": ["custom_idor_checker", "curl"],
      "payloads": ["id=2", "id=0", "id=99999"],
      "estimated_time": 120
    }}
  ],
  "custom_templates_needed": [
    {{
      "tech": "WordPress 6.x",
      "check_description": "WP REST API user enumeration",
      "severity": "medium"
    }}
  ],
  "high_value_endpoints": ["/wp-admin/", "/api/", "/login"],
  "technologies_of_interest": ["WordPress", "nginx 1.24"],
  "waf_bypass_strategies": ["Cloudflare: use IP rotation, chunked encoding"]
}}
"""

        # ── P3-4: Token budget management — trim prompt if over 8K tokens ──
        TOKEN_BUDGET = 8000
        estimated_tokens = len(prompt) // 4
        if estimated_tokens > TOKEN_BUDGET:
            # Aggressively trim: fewer subs, fewer URL patterns, smaller OSINT
            trim_ratio = TOKEN_BUDGET / estimated_tokens
            logger.info(
                f"Strategic planning prompt over budget ({estimated_tokens} est. tokens > {TOKEN_BUDGET}). "
                f"Trimming recon data by {1 - trim_ratio:.0%}."
            )
            # Rebuild with tighter limits
            sub_limit = max(5, int(len(interesting_subs) * trim_ratio))
            url_limit = max(10, int(len(url_lines) * trim_ratio))
            dns_limit = max(3, int(8 * trim_ratio))
            osint_limit = max(300, int(1500 * trim_ratio))

            trimmed_subs = interesting_subs[:sub_limit]
            trimmed_urls = chr(10).join(url_lines[:url_limit])
            trimmed_dns = json.dumps(dns_records[:dns_limit], indent=1, default=str)
            trimmed_osint = osint_str[:osint_limit]

            prompt = f"""## Task: Strategic Attack Planning

You are an elite bug bounty hunter analyzing reconnaissance data for {target}.
Create a prioritized attack plan identifying the most promising vulnerability vectors.

### Reconnaissance Summary (condensed)

**Subdomains ({len(subdomains)} found, showing {len(trimmed_subs)}):**
{chr(10).join(f'  - {s}' for s in trimmed_subs)}

**Live Hosts ({len(live_hosts)} total):** {', '.join(live_hosts[:5])}{'...' if len(live_hosts) > 5 else ''}

**Tech Stack:** {json.dumps(tech_compact)}

**Ports:** std={port_compact.get('standard', [])}, other={port_compact.get('non_standard', [])}

**DNS ({len(dns_records)}):** {trimmed_dns}

**URL Patterns ({len(urls)} URLs, {len(url_clusters)} patterns):**
{trimmed_urls}

**OSINT:** {trimmed_osint}

### Produce JSON with: summary, attack_vectors (top 10, each with endpoint/parameter/vuln_type/priority/reasoning/tools/payloads/estimated_time), custom_templates_needed, high_value_endpoints, technologies_of_interest, waf_bypass_strategies."""

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are an expert bug bounty hunter with 10+ years of experience on HackerOne and Bugcrowd. "
                "You analyze reconnaissance data and create highly targeted, actionable attack plans. "
                "Focus on vulnerabilities that are ACTUALLY exploitable and would be accepted by bug bounty programs. "
                "Avoid generic findings like missing headers — focus on impact."
            ),
            brain=BrainType.PRIMARY,
            timeout=1800.0,
            task_type="strategy",
        )

        return self._parse_intelligence_plan_from_dict(data, target)

    # ── 1b. Creative Attack Narratives (Pre-Hoc Strategist) ───────

    async def generate_creative_attack_narratives(
        self,
        target: str,
        technologies: dict[str, list[str]],
        endpoints: list[str],
        auth_info: dict[str, Any] | None = None,
    ) -> list[dict[str, str]]:
        """
        V6-T0-2: LLM as Pre-Hoc Strategist.

        Instead of forcing JSON, the LLM thinks freely about the application
        like a real bug bounty hunter. It produces creative attack narratives
        that describe exploitation scenarios in plain language. These narratives
        are then parsed for actionable attack ideas.

        Returns a list of dicts with keys: narrative, vuln_class, target_endpoint, severity_estimate.
        """
        if not self.is_available:
            logger.info("generate_creative_attack_narratives skipped: brain unavailable")
            return []

        # Build a compact picture of what we know about the target
        tech_lines = []
        for host, techs in list(technologies.items())[:8]:
            tech_lines.append(f"  {host}: {', '.join(techs[:5])}")
        tech_block = "\n".join(tech_lines) if tech_lines else "  (unknown)"

        # Categorize endpoints by type for better LLM comprehension
        api_eps = [e for e in endpoints if "/api/" in e or "/v1/" in e or "/v2/" in e or "/graphql" in e]
        auth_eps = [e for e in endpoints if any(k in e.lower() for k in ("login", "auth", "oauth", "token", "register", "signup", "password", "session"))]
        upload_eps = [e for e in endpoints if any(k in e.lower() for k in ("upload", "import", "file", "attach", "media"))]
        payment_eps = [e for e in endpoints if any(k in e.lower() for k in ("pay", "checkout", "cart", "order", "billing", "invoice", "subscription"))]
        admin_eps = [e for e in endpoints if any(k in e.lower() for k in ("admin", "manage", "dashboard", "internal", "staff", "config"))]
        other_eps = [e for e in endpoints[:30] if e not in api_eps + auth_eps + upload_eps + payment_eps + admin_eps]

        def _fmt(lst: list[str], limit: int = 10) -> str:
            if not lst:
                return "  (none found)"
            return "\n".join(f"  - {u}" for u in lst[:limit])

        prompt = f"""You are an elite bug bounty hunter sitting down to study a target before attacking.
You have completed reconnaissance on {target}. Below is what you know.

## Technology Stack
{tech_block}

## API Endpoints ({len(api_eps)} found)
{_fmt(api_eps)}

## Authentication Endpoints ({len(auth_eps)} found)
{_fmt(auth_eps)}

## File Upload Endpoints ({len(upload_eps)} found)
{_fmt(upload_eps)}

## Payment/Commerce Endpoints ({len(payment_eps)} found)
{_fmt(payment_eps)}

## Admin/Internal Endpoints ({len(admin_eps)} found)
{_fmt(admin_eps)}

## Other Notable Endpoints
{_fmt(other_eps)}

{f"## Authentication Context" + chr(10) + json.dumps(auth_info, indent=2, default=str)[:1000] if auth_info else ""}

---

**Your task:** Think like a creative hacker. Do NOT generate JSON. Write freely.

For each idea, think about:
- What could go wrong if a developer made a common mistake here?
- What happens if I send unexpected input? Negative numbers? Extra fields? Different encodings?
- Are there any interesting state transitions (e.g., payment → order → fulfill)?
- Can I abuse multi-step flows by skipping steps, replaying requests, or racing?
- What interesting data might leak from error messages, debug endpoints, or response headers?
- Could authorization checks be weak, missing, or bypassable for some endpoints?

Write 5-10 creative attack scenarios. For each one:
1. Describe the attack idea as a short narrative paragraph (2-4 sentences)
2. State the vulnerability class (e.g., "IDOR", "Race Condition", "Mass Assignment")
3. Name the specific endpoint(s) to target
4. Estimate severity (Critical/High/Medium/Low)

Format each scenario like:
---
SCENARIO: [title]
NARRATIVE: [your creative attack description]
VULN_CLASS: [vulnerability type]
ENDPOINT: [specific endpoint]
SEVERITY: [Critical/High/Medium/Low]
---
"""

        response = await self._brain_call(
            prompt,
            system_prompt=(
                "You are a creative, experienced bug bounty hunter who thinks outside the box. "
                "You do NOT just run automated scanners — you study the application, understand its logic, "
                "and come up with creative attack scenarios that scanners would miss. "
                "Write freely in plain English. Be specific about endpoints and parameters. "
                "Focus on HIGH-IMPACT bugs that programs actually pay for: IDOR, auth bypass, "
                "business logic flaws, race conditions, SSRF, mass assignment, privilege escalation."
            ),
            brain=BrainType.PRIMARY,
            json_mode=False,  # Free-think mode — no JSON constraint
            timeout=1800.0,
            task_type="strategy",
        )

        return self._parse_attack_narratives(response)

    def _parse_attack_narratives(self, text: str) -> list[dict[str, str]]:
        """Parse free-form attack narratives from LLM response."""
        if not text:
            return []

        narratives: list[dict[str, str]] = []
        # Split on "SCENARIO:" or "---" delimiters
        import re as _re
        blocks = _re.split(r'(?:^|\n)---\s*\n|(?:^|\n)SCENARIO:', text)

        for block in blocks:
            block = block.strip()
            if not block or len(block) < 30:
                continue

            narrative_m = _re.search(r'NARRATIVE:\s*(.+?)(?=\nVULN_CLASS:|\nENDPOINT:|\nSEVERITY:|\Z)', block, _re.DOTALL)
            vuln_m = _re.search(r'VULN_CLASS:\s*(.+?)(?=\n|$)', block)
            endpoint_m = _re.search(r'ENDPOINT:\s*(.+?)(?=\n|$)', block)
            severity_m = _re.search(r'SEVERITY:\s*(.+?)(?=\n|$)', block)

            narrative_text = narrative_m.group(1).strip() if narrative_m else block[:200]
            vuln_class = vuln_m.group(1).strip() if vuln_m else "unknown"
            endpoint = endpoint_m.group(1).strip() if endpoint_m else ""
            severity = severity_m.group(1).strip() if severity_m else "medium"

            if narrative_text:
                narratives.append({
                    "narrative": narrative_text,
                    "vuln_class": vuln_class,
                    "target_endpoint": endpoint,
                    "severity_estimate": (severity or "medium").lower(),
                })

        logger.info(f"🧠 Creative strategist produced {len(narratives)} attack narratives")
        for i, n in enumerate(narratives[:5]):
            logger.info(
                f"  💡 Narrative #{i+1}: [{n['severity_estimate']}] {n['vuln_class']} "
                f"→ {n['target_endpoint'][:60]} — {n['narrative'][:80]}..."
            )
        return narratives

    # ── 1c. Dynamic Test Case Generation for Checkers ─────────────

    async def generate_dynamic_test_cases(
        self,
        target: str,
        endpoints: list[str],
        technologies: dict[str, list[str]],
        checker_type: str,  # "idor", "business_logic", "race_condition"
    ) -> list[dict[str, Any]]:
        """
        V6-T0-4: LLM-generated test cases for IDOR, business logic, and race condition checkers.

        Instead of relying on regex or hardcoded endpoints, asks the LLM to analyze
        the discovered endpoints and generate contextually-appropriate test cases
        that the respective checker can execute.
        """
        if not self.is_available:
            logger.info(f"generate_dynamic_test_cases({checker_type}) skipped: brain unavailable")
            return []

        # Group endpoints by likely function
        ep_sample = endpoints[:50]
        ep_text = "\n".join(f"  - {e}" for e in ep_sample)

        if checker_type == "idor":
            prompt = f"""## Task: Generate IDOR Test Cases

Target: {target}
Discovered Endpoints ({len(endpoints)} total, showing {len(ep_sample)}):
{ep_text}

Analyze these endpoints and identify which ones likely have IDOR (Insecure Direct Object Reference) vulnerabilities.

For EACH promising endpoint, generate a test case with:
- The URL to test
- The HTTP method (GET, POST, PUT, DELETE, PATCH)
- The parameter name that contains the object reference (e.g., "id", "user_id", "order_id")
- The original value (extract from URL or guess a plausible value like "1")
- Test values to try (sequential IDs, UUIDs, negative values, zero, very large numbers)
- The expected behavior if IDOR exists vs. if properly authorized

Focus on:
1. Numeric IDs in path or query: /api/users/123, ?user_id=456
2. UUID references: /api/documents/abc-def-...
3. Encoded references: base64 or hex IDs
4. Composite keys: /api/org/1/user/2

Return JSON array:
```json
[
  {{
    "url": "https://example.com/api/users/1",
    "method": "GET",
    "param_name": "user_id",
    "original_value": "1",
    "test_values": ["0", "2", "3", "99999", "-1"],
    "description": "User profile endpoint with sequential numeric ID"
  }}
]
```"""

        elif checker_type == "business_logic":
            prompt = f"""## Task: Generate Business Logic Test Definitions

Target: {target}
Discovered Endpoints ({len(endpoints)} total, showing {len(ep_sample)}):
{ep_text}

Analyze these endpoints and identify business logic vulnerabilities to test.

Generate test definitions for:
1. **Price manipulation** — endpoints handling money/prices/quantities
2. **Workflow bypass** — multi-step processes where steps can be skipped
3. **Privilege escalation** — changing role/permissions via parameter tampering
4. **Rate limit bypass** — coupon/promo/referral abuse
5. **Quantity manipulation** — negative quantities, extreme values

For EACH test, specify:
- The endpoint URL
- The test type (price, quantity, workflow, privilege, rate_limit)
- The HTTP method
- The body parameters to manipulate
- The manipulation values to try
- What success looks like (e.g., "price becomes 0", "admin access gained")

Return JSON array:
```json
[
  {{
    "type": "price",
    "url": "https://example.com/api/checkout",
    "method": "POST",
    "param": "total_price",
    "test_values": [0, -1, 0.01, 99999999],
    "description": "Checkout endpoint allows direct price parameter in body"
  }}
]
```"""

        elif checker_type == "race_condition":
            prompt = f"""## Task: Generate Race Condition Test Cases

Target: {target}
Discovered Endpoints ({len(endpoints)} total, showing {len(ep_sample)}):
{ep_text}

Identify endpoints vulnerable to race conditions (TOCTOU bugs).

Race conditions are most common in:
1. **Financial transactions** — double-spend, balance manipulation
2. **Invitation/referral systems** — redeem multiple times
3. **Coupon/promo codes** — apply once but race to apply twice
4. **Vote/like systems** — inflate counts
5. **Rate-limited actions** — bypass limits via concurrent requests
6. **Account creation** — duplicate accounts with same email

For EACH potential race condition:
- The endpoint URL
- The HTTP method
- The request body/parameters
- The concurrency level to use (how many parallel requests)
- Number of test rounds
- What to check after the race (balance, count, status)

Return JSON array:
```json
[
  {{
    "url": "https://example.com/api/transfer",
    "method": "POST",
    "body": {{"to": "user2", "amount": 100}},
    "concurrency": 20,
    "rounds": 3,
    "check_endpoint": "https://example.com/api/balance",
    "description": "Money transfer - race to overdraw balance"
  }}
]
```"""
        else:
            return []

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are an expert security tester specializing in application logic vulnerabilities. "
                "Analyze the given endpoints carefully and generate specific, actionable test cases. "
                "Only include endpoints that genuinely look promising — quality over quantity."
            ),
            brain=BrainType.PRIMARY,
            timeout=1200.0,
            task_type="analyze",
        )

        if isinstance(data, list):
            logger.info(f"🧠 Generated {len(data)} dynamic {checker_type} test cases")
            return data
        if isinstance(data, dict) and "test_cases" in data:
            cases = data["test_cases"]
            logger.info(f"🧠 Generated {len(cases)} dynamic {checker_type} test cases")
            return cases
        logger.warning(
            f"Dynamic {checker_type} test case generation returned unparseable response "
            f"(type={type(data).__name__})"
        )
        return []

    async def decide_next_action(
        self,
        current_stage: str,
        findings_so_far: list[dict[str, Any]],
        completed_tools: list[str],
        remaining_tools: list[str],
        time_elapsed: str = "",
        scan_profile: str = "balanced",
        historical_learning: dict[str, Any] | None = None,
    ) -> NextActionDecision:
        """Decide the safest, highest-value next action within the current stage.

        This is a controlled branch point for agentic execution. The model can only
        prioritize or skip tools already known to the pipeline and point the scan at
        a specific deep-dive target.
        """
        if not self.is_available:
            return NextActionDecision()

        from src.brain.prompts import TRIAGE_SYSTEM_PROMPT, build_next_action_prompt

        prompt = build_next_action_prompt(
            current_stage=current_stage,
            findings_so_far=findings_so_far,
            completed_tools=completed_tools,
            remaining_tools=remaining_tools,
            time_elapsed=time_elapsed,
            scan_profile=scan_profile,
            historical_learning=historical_learning,
        )

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                TRIAGE_SYSTEM_PROMPT
                + "\nYou are operating inside a fixed security pipeline. Only choose from the "
                "provided remaining tools. Prefer concrete, safe, high-ROI decisions: tool skipping, "
                "specific endpoint focus, or recommending a deeper probe."
            ),
            brain=BrainType.SECONDARY,
            timeout=1200.0,
            task_type="triage",
        ) or {}
        allowed_actions = {
            "continue", "skip_to_next_stage", "deep_dive", "pause", "complete",
            "deep_dive_tool", "change_strategy", "retry_with_auth", "request_oob_check",
        }
        action = str(data.get("action", "continue") or "continue").strip().lower()
        if action not in allowed_actions:
            action = "continue"

        skip_tools: list[str] = []
        for tool_name in data.get("skip_tools") or []:
            normalized = str(tool_name or "").strip().lower()
            if normalized:
                skip_tools.append(normalized)

        # P3-2: Validate change_strategy values
        strategy = str(data.get("change_strategy", "") or "").strip().lower()
        if strategy and strategy not in ("stealth", "balanced", "aggressive"):
            strategy = ""

        return NextActionDecision(
            action=action,
            reason=str(data.get("reason", "") or ""),
            next_tool=str(data.get("next_tool", "") or "").strip().lower(),
            skip_tools=list(dict.fromkeys(skip_tools)),
            deep_dive_target=str(data.get("deep_dive_target", "") or "").strip(),
            deep_dive_tool=str(data.get("deep_dive_tool", "") or "").strip().lower(),
            change_strategy=strategy,
            retry_with_auth=bool(data.get("retry_with_auth", False)),
            request_oob_check=bool(data.get("request_oob_check", False)),
            stage_transition=str(data.get("stage_transition", "") or "").strip(),
            priority_findings=[str(x) for x in (data.get("priority_findings") or []) if str(x).strip()],
            time_estimate=str(data.get("time_estimate", "") or "").strip(),
        )

    # ── 2. Dynamic Tool Configuration ─────────────────────────────

    async def suggest_tool_config(
        self,
        tool_name: str,
        target: str,
        context: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Ask the LLM to suggest optimal tool configuration for this target.
        Uses Secondary brain (20B) for fast decisions.
        """
        if not self.is_available:
            return {}

        prompt = f"""## Task: Optimize Tool Configuration

For target: {target}
Tool: {tool_name}

Context:
{json.dumps(context, indent=2, default=str)[:3000]}

What are the OPTIMAL settings for this tool on this target?
Consider: WAF evasion, rate limiting, target technology, scope constraints.

Return JSON with tool-specific options:
```json
{{
  "options": {{"key": "value"}},
  "reasoning": "why these settings"
}}
```
"""

        data = await self._brain_call_json(
            prompt,
            system_prompt="You are a security tool expert. Suggest optimal configurations.",
            brain=BrainType.SECONDARY,
            task_type="tool_select",
        )

        return data.get("options", {}) if data else {}

    # ── 3. Tool Output Analysis ───────────────────────────────────

    async def analyze_tool_output(
        self,
        tool_name: str,
        target: str,
        raw_output: str,
        parsed_findings: list[dict],
        context: dict[str, Any] | None = None,
    ) -> list[dict]:
        """
        Have the LLM analyze raw tool output to find subtle vulnerabilities
        that automated parsers might miss. This is what separates a hunter
        from a scanner.

        Uses Primary brain (32B) for deep analysis.
        """
        if not self.is_available:
            return []

        # Truncate output for model context
        output_preview = raw_output[:8000] if raw_output else "No output"

        prompt = f"""## Task: Deep Tool Output Analysis

Analyze the raw output from {tool_name} scanning {target}.
Look for subtle vulnerabilities that the automated parser might have MISSED.

### Raw Tool Output (truncated)
```
{output_preview}
```

### Already Parsed Findings ({len(parsed_findings)} found):
{json.dumps(parsed_findings[:5], indent=2, default=str)[:2000]}

### Analysis Requirements
1. Look for information disclosure in headers/responses
2. Identify potential injection points from error messages
3. Spot misconfigurations not flagged by the tool
4. Identify version-specific CVEs from service banners
5. Notice access control issues from response codes
6. Detect WAF-filtered responses that might hide vulns

### Response (JSON)
```json
{{
  "additional_findings": [
    {{
      "title": "Potential SSRF via redirect parameter",
      "type": "ssrf",
      "severity": "high",
      "evidence": "Location header redirects to internal IP",
      "endpoint": "/api/proxy?url=",
      "recommended_test": "curl -v 'https://target/api/proxy?url=http://169.254.169.254/'"
    }}
  ],
  "interesting_observations": ["Server reveals internal IPs in X-Forwarded-For"],
  "suggested_follow_up": ["Test /api/proxy with SSRF payloads"]
}}
```
"""

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are an expert security researcher analyzing tool output. "
                "Think like a bug bounty hunter — look for what automated tools miss. "
                "Focus on ACTIONABLE findings."
            ),
            brain=BrainType.PRIMARY,
            task_type="analyze",
        )

        return data.get("additional_findings", []) if data else []

    # ── 4. Evidence Verification ──────────────────────────────────

    async def verify_finding(
        self,
        finding: dict,
        http_request: str = "",
        http_response: str = "",
        response_diff: str = "",
    ) -> VerificationResult:
        """
        Have the LLM deeply analyze a finding's evidence to determine
        if it's real, a false positive, or needs more testing.

        This is where the bot acts like a human researcher —
        actually reading the HTTP exchange and understanding context.

        Uses Primary brain (32B) for maximum accuracy.
        """
        if not self.is_available:
            return VerificationResult()

        prompt = f"""## Task: Vulnerability Verification

Carefully analyze this finding and determine if it's a REAL vulnerability.
Think step by step — examine the evidence like an experienced bug bounty hunter.

### Finding
- **Title:** {finding.get('title', 'Unknown')}
- **Type:** {finding.get('vulnerability_type', finding.get('type', 'unknown'))}
- **Severity:** {finding.get('severity', 'unknown')}
- **Tool:** {finding.get('tool_name', finding.get('tool', 'unknown'))}
- **URL:** {finding.get('target', finding.get('endpoint', finding.get('url', 'N/A')))}
- **Parameter:** {finding.get('parameter', 'N/A')}
- **Payload:** {finding.get('payload', 'N/A')}
- **Evidence:** {finding.get('evidence', 'N/A')}

### HTTP Request
```
{http_request[:3000] if http_request else 'Not available'}
```

### HTTP Response
```
{http_response[:5000] if http_response else 'Not available'}
```

### Response Differential (normal vs payload)
```
{response_diff[:3000] if response_diff else 'Not available'}
```

### Verification Checklist
1. Does the payload actually execute/reflect in the response?
2. Is encoding applied that prevents exploitation?
3. Is this a WAF/CDN artifact rather than a real vuln?
4. Could this be a benign behavior being misinterpreted?
5. What is the actual exploitable impact?
6. What CVSS score would this get if accepted?
7. What PoC steps would prove this to a triager?

### Response (JSON)
```json
{{
  "is_real": true,
  "confidence": 85,
  "reasoning": "The XSS payload reflects unencoded in the response body within a script context...",
  "additional_evidence": "Response header X-XSS-Protection is set to 0",
  "suggested_poc_steps": [
    "1. Navigate to {finding.get('target', finding.get('endpoint', finding.get('url', 'URL')))}",
    "2. Inject payload in parameter X",
    "3. Observe JavaScript execution"
  ],
  "exploit_feasibility": "trivial",
  "cvss_override": 6.1
}}
```
"""

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are a senior security researcher verifying vulnerabilities. "
                "You must be RIGOROUS — accept only findings with clear, undeniable evidence. "
                "If in doubt, reject. Bug bounty programs penalize false reports. "
                "Think step by step."
            ),
            brain=BrainType.PRIMARY,
            task_type="fp_check",
        )

        return self._parse_verification_result_from_dict(data)

    # ── 5. Custom Nuclei Template Generation ──────────────────────

    async def generate_nuclei_template(
        self,
        tech: str,
        version: str = "",
        check_description: str = "",
        known_cve: str = "",
        example_request: str = "",
    ) -> NucleiTemplate | None:
        """
        Generate a custom nuclei YAML template for a specific technology
        or vulnerability pattern that isn't covered by community templates.

        Uses Primary brain (32B) for accurate YAML generation.
        """
        if not self.is_available:
            return None

        prompt = f"""## Task: Write Custom Nuclei Template

Create a nuclei YAML template to detect a specific vulnerability or misconfiguration.

### Target Technology
- **Technology:** {tech}
- **Version:** {version or "any"}
- **Check Description:** {check_description or "General security check"}
- **Known CVE:** {known_cve or "N/A"}
- **Example Request:** {example_request or "N/A"}

### CRITICAL: Exact Nuclei YAML Format

The template MUST follow this EXACT structure (nuclei v3 format):

```yaml
id: custom-example-check

info:
  name: Example Vulnerability Check
  author: custom
  severity: medium
  description: What this template detects
  tags: tag1,tag2

http:
  - method: GET
    path:
      - "{{{{BaseURL}}}}/target-path"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "match-string"
        part: body

      - type: status
        status:
          - 200
```

IMPORTANT RULES:
- Root keys are ONLY: id, info, http (or flow, code, etc.)
- "http:" is a root-level key (NOT nested under "template:" or "requests:")
- "matchers:" is nested UNDER each http request item, NOT at root level
- Paths MUST use {{{{BaseURL}}}} prefix
- NO "template:", "evidence:", or "requests:" at root level
- Use "http:" (not "requests:") as the root key for HTTP templates

### Response (JSON)
```json
{{
  "template_id": "custom-{tech.lower().replace(' ', '-')}-check",
  "name": "Description of what it detects",
  "severity": "medium",
  "description": "Detailed description",
  "yaml_content": "id: custom-check\\ninfo:\\n  name: Check Name\\n  author: custom\\n  severity: medium\\n  tags: custom\\nhttp:\\n  - method: GET\\n    path:\\n      - \\"{{{{BaseURL}}}}/path\\"\\n    matchers:\\n      - type: word\\n        words:\\n          - \\"match\\"\\n        part: body"
}}
```
"""

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are an expert nuclei template developer. "
                "Write valid nuclei v3 YAML templates. "
                "The YAML must use 'http:' as root key (NOT 'template:' or 'requests:'). "
                "Matchers go UNDER each http request item. Paths use {{BaseURL}}. "
                "Return valid JSON with yaml_content as a properly escaped YAML string."
            ),
            brain=BrainType.PRIMARY,
            task_type="exploit",
        )

        return self._parse_nuclei_template_from_dict(data, tech)

    # ── 6. Exploit / PoC Generation ───────────────────────────────

    async def generate_poc(
        self,
        finding: dict,
        http_request: str = "",
        http_response: str = "",
        language: str = "python",
    ) -> PoCScript | None:
        """
        Generate a Proof of Concept script that demonstrates the vulnerability.
        This is CRITICAL for bug bounty acceptance — you MUST have a working PoC.

        Uses Primary brain (32B) for code generation.
        """
        if not self.is_available:
            return None

        prompt = f"""## Task: Generate Proof of Concept

Create a self-contained PoC that PROVES this vulnerability exists.
The PoC must be safe, clean, and convincing for a bug bounty triager.

### Vulnerability Details
- **Title:** {finding.get('title', 'Unknown')}
- **Type:** {finding.get('vulnerability_type', finding.get('type', 'unknown'))}
- **URL:** {finding.get('target', finding.get('endpoint', finding.get('url', 'N/A')))}
- **Parameter:** {finding.get('parameter', 'N/A')}
- **Payload:** {finding.get('payload', 'N/A')}
- **Evidence:** {finding.get('evidence', 'N/A')}

### HTTP Request
```
{http_request[:3000] if http_request else 'Not available'}
```

### HTTP Response
```
{http_response[:3000] if http_response else 'Not available'}
```

### Requirements
1. SAFE payloads only (alert(1), sleep(5), pingback — NEVER destructive)
2. Self-contained {language} script with minimal dependencies
3. Clear output showing success/failure
4. An equivalent curl command for manual verification
5. Step-by-step browser instructions if applicable
6. Error handling and timeout
7. Comments explaining each step

### Response (JSON)
```json
{{
  "language": "{language}",
  "script_content": "#!/usr/bin/env python3\\nimport requests\\n...",
  "curl_command": "curl -v ...",
  "browser_steps": ["1. Open URL", "2. ...", "3. Observe ..."],
  "expected_output": "The script will show ... confirming ...",
  "dependencies": ["requests"]
}}
```
"""

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are a senior penetration tester writing proof-of-concept exploits. "
                "Your PoCs must be SAFE, CLEAN, and CONVINCING. "
                "They must prove the vulnerability without causing damage."
            ),
            brain=BrainType.PRIMARY,
            task_type="exploit",
        )

        return self._parse_poc_script_from_dict(data)

    # ── 7. Report Enrichment ──────────────────────────────────────

    async def enrich_report_finding(
        self,
        finding: dict,
        http_evidence: str = "",
    ) -> dict:
        """
        Enrich a finding with professional-grade narrative, impact analysis,
        CVSS justification, and remediation guidance.

        Uses Primary brain (32B) for professional writing.
        """
        if not self.is_available:
            return finding

        prompt = f"""## Task: Write Professional Bug Bounty Report Section

Write a professional, detailed report section for this vulnerability finding.
This is for a HackerOne/Bugcrowd submission — it must be clear, technical,
and convincing.

### Finding
{json.dumps(finding, indent=2, default=str)[:4000]}

### HTTP Evidence
```
{http_evidence[:3000] if http_evidence else 'Not available'}
```

### Requirements
1. Professional title (short, specific, impactful)
2. Clear 2-3 sentence summary
3. Accurate CVSS 3.1 score with vector string and justification
4. Detailed impact analysis (confidentiality, integrity, availability, business impact)
5. Step-by-step reproduction (numbered, exact URLs and parameters)
6. Specific, actionable remediation advice
7. Relevant CWE and OWASP references

### Response (JSON)
```json
{{
  "title": "Stored XSS in Profile Bio via Markdown Parser",
  "summary": "A stored cross-site scripting vulnerability...",
  "cvss_score": 6.1,
  "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N",
  "cvss_justification": "Network accessible, low complexity...",
  "impact": "An attacker could steal session cookies...",
  "steps_to_reproduce": ["1. Navigate to...", "2. In the bio field, enter...", "3. Save and observe..."],
  "remediation": "Sanitize markdown output using...",
  "cwe": "CWE-79: Improper Neutralization of Input During Web Page Generation",
  "owasp": "A7:2017-Cross-Site Scripting (XSS)"
}}
```
"""

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are an elite bug bounty hunter writing a report for HackerOne. "
                "Your reports are known for being clear, technical, and persuasive. "
                "Include specific technical details."
            ),
            brain=BrainType.PRIMARY,
            task_type="report",
        )

        if data:
            # Merge enrichment into finding
            # Clamp CVSS score to valid range
            raw_cvss = data.get("cvss_score", finding.get("cvss_score"))
            if raw_cvss is not None:
                try:
                    raw_cvss = max(0.0, min(10.0, float(raw_cvss)))
                except (ValueError, TypeError):
                    raw_cvss = finding.get("cvss_score")

            finding.update({
                "enriched_title": data.get("title", finding.get("title", "")),
                "enriched_summary": data.get("summary", ""),
                "cvss_score": raw_cvss,
                "cvss_vector": data.get("cvss_vector", ""),
                "cvss_justification": data.get("cvss_justification", ""),
                "enriched_impact": data.get("impact", ""),
                "enriched_steps": data.get("steps_to_reproduce", []),
                "enriched_remediation": data.get("remediation", ""),
                "cwe": data.get("cwe", finding.get("cwe", "")),
                "owasp": data.get("owasp", ""),
            })

        return finding

    # ── 8. Adaptive Re-scan Decision ──────────────────────────────

    async def decide_rescan_strategy(
        self,
        completed_findings: list[dict],
        failed_tools: list[str],
        remaining_time_seconds: int,
        endpoints: list[str],
    ) -> dict:
        """
        After initial scanning, decide what to re-test or test differently.
        This is the "human intuition" — a real hunter doesn't just run tools
        once, they iterate based on what they find.

        Uses Secondary brain (20B) for fast decisions.
        """
        if not self.is_available:
            return {"rescan_needed": False}

        prompt = f"""## Task: Decide Re-scan Strategy

Based on initial scan results, decide what needs additional testing.

### Current Findings ({len(completed_findings)})
{json.dumps(completed_findings[:10], indent=2, default=str)[:3000]}

### Failed Tools
{json.dumps(failed_tools)}

### Remaining Time: {remaining_time_seconds}s
### Available Endpoints: {len(endpoints)}

What should we test again or differently? Focus on:
1. Findings that need deeper verification
2. Endpoints from failed tools that should be retried
3. Interesting patterns that need different tool/payload

Response (JSON):
```json
{{
  "rescan_needed": true,
  "priority_retests": [
    {{
      "endpoint": "/api/v1/users",
      "tool": "sqlmap",
      "reason": "Previous test timed out, high-value endpoint",
      "options": {{"level": 5, "risk": 3}}
    }}
  ],
  "new_tests": [
    {{
      "endpoint": "/api/graphql",
      "tool": "graphql_introspection",
      "reason": "GraphQL endpoint discovered but not tested"
    }}
  ]
}}
```
"""

        data = await self._brain_call_json(
            prompt,
            system_prompt="You are a bug bounty strategist. Decide what needs re-testing.",
            brain=BrainType.SECONDARY,
            task_type="triage",
        )

        return data if data else {"rescan_needed": False}

    # ── Internal Helpers ──────────────────────────────────────────

    async def _brain_call_json(
        self,
        prompt: str,
        system_prompt: str = "",
        brain: BrainType = BrainType.PRIMARY,
        timeout: float = 1200.0,
        task_type: str = "",
    ) -> dict | list | None:
        """Brain call that guarantees parsed JSON — retries once on parse failure.

        Returns parsed dict/list on success, None on failure. This replaces the
        pattern of `_brain_call(json_mode=True)` + `_safe_json_parse()` with
        a single call that automatically retries with a correction prompt if
        the first response isn't valid JSON.
        """
        response = await self._brain_call(
            prompt=prompt,
            system_prompt=system_prompt,
            brain=brain,
            json_mode=True,
            timeout=timeout,
            task_type=task_type,
        )

        if not response:
            self._json_parse_fail += 1
            return None

        # Try parsing the response
        data = self._safe_json_parse(response)
        if data is not None:
            self._json_parse_ok += 1
            return data

        # Parse failed — retry once with explicit correction prompt
        logger.warning(
            f"Intelligence JSON parse failed (#{self._call_count}), "
            f"retrying with correction prompt | response_preview={response[:200]!r}"
        )

        correction_prompt = (
            "Your previous response was NOT valid JSON and could not be parsed.\n"
            f"Here is what you returned (first 500 chars):\n{response[:500]}\n\n"
            "Please return ONLY the corrected, valid JSON. "
            "No markdown fences, no text outside the JSON. "
            "If the data is a list, start with [ and end with ]. "
            "If the data is an object, start with {{ and end with }}."
        )

        retry_response = await self._brain_call(
            prompt=correction_prompt,
            system_prompt=system_prompt,
            brain=brain,
            json_mode=True,
            timeout=min(timeout, 120.0),
            task_type=task_type,
        )

        if retry_response:
            data = self._safe_json_parse(retry_response)
            if data is not None:
                self._json_parse_retry_ok += 1
                logger.info(f"Intelligence JSON retry succeeded (#{self._call_count})")
                return data

        self._json_parse_fail += 1
        logger.warning(f"Intelligence JSON retry also failed (#{self._call_count})")
        return None

    async def _brain_call(
        self,
        prompt: str,
        system_prompt: str = "",
        brain: BrainType = BrainType.PRIMARY,
        json_mode: bool = False,
        timeout: float = 1200.0,
        task_type: str = "",
    ) -> str:
        """Wrapped brain.think() call with logging, timing, caching and error handling."""
        # Route via BrainRouter if available and task_type is specified
        if self.router and task_type:
            brain = self.router.route(task_type)

        # Guard: skip immediately if brain is confirmed down
        if not self.is_available:
            return ""

        self._call_count += 1
        t0 = time.time()

        # E1: Check cache for identical prompts
        cache_key = hashlib.sha256(
            f"{brain.value}:{system_prompt}:{prompt}:{json_mode}".encode()
        ).hexdigest()[:16]

        async with self._cache_lock:
            if cache_key in self._cache:
                cached_text, cached_time = self._cache[cache_key]
                if (time.time() - cached_time) < self._cache_ttl:
                    self._cache_hits += 1
                    self._cache.move_to_end(cache_key)  # LRU: most recent at end
                    logger.info(
                        f"Intelligence call #{self._call_count} CACHE HIT | "
                        f"brain={brain.value} | hits={self._cache_hits}"
                    )
                    return cached_text
                else:
                    # Expired entry
                    del self._cache[cache_key]

        try:
            # Sanitize credentials from prompt content before sending to LLM
            sanitized_prompt = _sanitize_prompt(prompt)
            sanitized_system = _sanitize_prompt(system_prompt)

            response: BrainResponse = await asyncio.wait_for(
                self.brain.think(
                    prompt=sanitized_prompt,
                    brain=brain,
                    system_prompt=sanitized_system,
                    json_mode=json_mode,
                ),
                timeout=timeout,
            )
            elapsed = time.time() - t0
            self._total_time += elapsed

            logger.info(
                f"Intelligence call #{self._call_count} | "
                f"brain={brain.value} | time={elapsed:.1f}s | "
                f"tokens={response.tokens_used} | "
                f"text_len={len(response.text)}"
            )

            self._brain_call_success += 1

            # Cache successful non-empty responses
            if response.text.strip():
                async with self._cache_lock:
                    if len(self._cache) >= self._cache_max_size:
                        # Evict least-recently-used entry (first in order)
                        self._cache.popitem(last=False)
                    self._cache[cache_key] = (response.text, time.time())
                # Reset failure counter on success
                self._consecutive_failures = 0

            # D3: Log brain CoT thinking content if available
            if response.metadata.get("thinking"):
                logger.debug(
                    f"Brain thinking (#{self._call_count}): "
                    f"{response.metadata['thinking'][:300]}..."
                )

            # Track empty responses
            if not response.text.strip():
                self._brain_call_empty += 1

            return response.text

        except asyncio.TimeoutError:
            elapsed = time.time() - t0
            # H4 fix: retry once with 60% timeout before giving up
            retry_timeout = timeout * 0.6
            if not self._brain_down and retry_timeout >= 15:
                logger.info(
                    f"Intelligence call #{self._call_count} timed out after {elapsed:.1f}s, "
                    f"retrying with {retry_timeout:.0f}s timeout"
                )
                try:
                    response = await asyncio.wait_for(
                        self.brain.think(
                            prompt=sanitized_prompt, brain=brain,
                            system_prompt=sanitized_system, json_mode=json_mode,
                        ),
                        timeout=retry_timeout,
                    )
                    if response.text.strip():
                        self._consecutive_failures = 0
                        async with self._cache_lock:
                            if len(self._cache) >= self._cache_max_size:
                                self._cache.popitem(last=False)
                            self._cache[cache_key] = (response.text, time.time())
                        logger.info(f"Intelligence call #{self._call_count} retry succeeded")
                        return response.text
                except (asyncio.TimeoutError, Exception) as _retry_err:
                    logger.debug("Intelligence retry also failed: %s", _retry_err)

            self._consecutive_failures += 1
            self._check_brain_down()
            self._brain_call_error += 1
            return ""
        except (RuntimeError, ConnectionError, OSError) as e:
            elapsed = time.time() - t0
            self._consecutive_failures += 1
            logger.warning(
                f"Intelligence call #{self._call_count} failed | "
                f"brain={brain.value} | time={elapsed:.1f}s | error={type(e).__name__}: {e} | "
                f"consecutive_failures={self._consecutive_failures}"
            )
            self._check_brain_down()
            self._brain_call_error += 1
            # Re-raise critical errors that indicate no model is available
            if isinstance(e, RuntimeError) and "No brain model available" in str(e):
                self._brain_down = True
                logger.error("Brain confirmed DOWN — No brain model available. All future brain calls will be skipped.")
                raise
            return ""
        except Exception as e:
            elapsed = time.time() - t0
            self._consecutive_failures += 1
            logger.error(
                f"Intelligence call #{self._call_count} unexpected error | "
                f"brain={brain.value} | time={elapsed:.1f}s | error={type(e).__name__}: {e} | "
                f"consecutive_failures={self._consecutive_failures}"
            )
            self._check_brain_down()
            self._brain_call_error += 1
            return ""

    def _check_brain_down(self) -> None:
        """B2: Mark brain as down after N consecutive failures."""
        if self._consecutive_failures >= self._brain_down_threshold and not self._brain_down:
            self._brain_down = True
            self._brain_down_time = time.time()
            logger.error(
                f"Brain marked as DOWN after {self._consecutive_failures} consecutive failures. "
                f"Will auto-retry after {self._brain_down_recovery_secs:.0f}s. "
                f"All intelligence calls will be skipped until then."
            )

    def _safe_json_parse(self, text: str) -> dict | list | None:
        """Parse JSON from LLM response, handling markdown code blocks.
        
        May return a dict OR a list depending on the LLM response.
        """
        if not text:
            return None

        # Try direct parse first
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        # Extract from markdown code block
        patterns = [
            r'```json\s*\n(.*?)\n```',
            r'```\s*\n(.*?)\n```',
        ]

        for pattern in patterns:
            match = re.search(pattern, text, re.DOTALL)
            if match:
                try:
                    candidate = match.group(1)
                    return json.loads(candidate)
                except (json.JSONDecodeError, IndexError):
                    continue

        # Find valid { ... } or [ ... ] using shared robust JSON extractor
        from src.utils.json_utils import extract_json
        # Try object first, then array
        result = extract_json(text, log_failures=False)
        if result is not None:
            return result
        return extract_json(text, expect_array=True, log_failures=True)

    def _parse_intelligence_plan(self, text: str, target: str) -> IntelligencePlan:
        """Parse LLM response into IntelligencePlan."""
        data = self._safe_json_parse(text)
        return self._parse_intelligence_plan_from_dict(data, target)

    def _parse_intelligence_plan_from_dict(self, data: dict | None, target: str) -> IntelligencePlan:
        """Parse dict into IntelligencePlan."""
        if not data:
            return IntelligencePlan(target=target)

        vectors = []
        for v in data.get("attack_vectors", []):
            try:
                vectors.append(AttackVector(
                    endpoint=v.get("endpoint", ""),
                    parameter=v.get("parameter", ""),
                    vuln_type=v.get("vuln_type", ""),
                    priority=v.get("priority", "medium"),
                    reasoning=v.get("reasoning", ""),
                    tools=v.get("tools", []),
                    payloads=v.get("payloads", []),
                    estimated_time=v.get("estimated_time", 60),
                ))
            except Exception as _exc:
                logger.warning(f"intelligence error: {_exc}")
                continue

        return IntelligencePlan(
            target=target,
            summary=data.get("summary", ""),
            attack_vectors=vectors,
            custom_templates_needed=data.get("custom_templates_needed", []),
            high_value_endpoints=data.get("high_value_endpoints", []),
            technologies_of_interest=data.get("technologies_of_interest", []),
            waf_bypass_strategies=data.get("waf_bypass_strategies", []),
        )

    def _parse_verification_result(self, text: str) -> VerificationResult:
        """Parse LLM response into VerificationResult."""
        data = self._safe_json_parse(text)
        return self._parse_verification_result_from_dict(data)

    def _parse_verification_result_from_dict(self, data: dict | None) -> VerificationResult:
        """Parse dict into VerificationResult."""
        if not data:
            return VerificationResult()

        def _sf(v: Any, d: float = 0.0) -> float:
            if v is None:
                return d
            try:
                return float(v)
            except (ValueError, TypeError):
                return d

        cvss_val = data.get("cvss_override")
        cvss_override: float | None = None
        if cvss_val is not None:
            parsed = _sf(cvss_val, -1.0)
            if parsed >= 0.0:
                cvss_override = max(0.0, min(10.0, parsed))

        return VerificationResult(
            is_real=bool(data.get("is_real", False)),
            confidence=max(0.0, min(100.0, _sf(data.get("confidence", 0), 0.0))),  # Bug 5.2l-5: was 50/50.0
            reasoning=str(data.get("reasoning", "") or ""),
            additional_evidence=str(data.get("additional_evidence", "") or ""),
            suggested_poc_steps=data.get("suggested_poc_steps") or [],
            exploit_feasibility=str(data.get("exploit_feasibility", "unknown") or "unknown"),
            cvss_override=cvss_override,
        )

    def _parse_nuclei_template(self, text: str, tech: str) -> NucleiTemplate | None:
        """Parse LLM response into NucleiTemplate, with YAML structure validation."""
        data = self._safe_json_parse(text)
        return self._parse_nuclei_template_from_dict(data, tech)

    def _parse_nuclei_template_from_dict(self, data: dict | None, tech: str) -> NucleiTemplate | None:
        """Parse dict into NucleiTemplate, with YAML structure validation."""
        if not data or not data.get("yaml_content"):
            return None

        yaml_content = data["yaml_content"]

        # ── Validate nuclei YAML structure ──
        try:
            import yaml as _yaml
            parsed = _yaml.safe_load(yaml_content)
            if not isinstance(parsed, dict):
                logger.warning("Nuclei template: YAML did not parse to dict")
                return None

            # Must have 'id' and 'info' at root
            if "id" not in parsed or "info" not in parsed:
                logger.warning("Nuclei template: missing 'id' or 'info' at root level")
                return None

            # Must have 'http' (or 'network', 'dns', 'headless', 'code', 'flow')
            valid_protocol_keys = {"http", "network", "dns", "headless", "code", "flow", "tcp", "ssl"}
            if not any(k in parsed for k in valid_protocol_keys):
                # Try to auto-fix: if "requests" or "template" key exists, restructure
                if "template" in parsed and isinstance(parsed["template"], dict):
                    inner = parsed["template"]
                    if "requests" in inner:
                        parsed["http"] = inner["requests"]
                        del parsed["template"]
                        logger.info("Nuclei template: auto-fixed 'template.requests' → 'http'")
                elif "requests" in parsed:
                    parsed["http"] = parsed.pop("requests")
                    logger.info("Nuclei template: auto-fixed 'requests' → 'http'")
                else:
                    logger.warning("Nuclei template: no protocol key (http/network/etc.) found")
                    return None

                # Remove non-standard root keys
                for bad_key in ("matchers", "evidence", "template"):
                    parsed.pop(bad_key, None)

                # Re-serialize the fixed YAML
                yaml_content = _yaml.dump(parsed, default_flow_style=False, sort_keys=False)

        except Exception as e:
            logger.warning(f"Nuclei template YAML validation failed: {e}")
            return None

        return NucleiTemplate(
            template_id=data.get("template_id", f"custom-{tech.lower().replace(' ', '-')}"),
            name=data.get("name", ""),
            severity=data.get("severity", "medium"),
            description=data.get("description", ""),
            yaml_content=yaml_content,
            target_tech=tech,
        )

    def _parse_poc_script(self, text: str) -> PoCScript | None:
        """Parse LLM response into PoCScript."""
        data = self._safe_json_parse(text)
        return self._parse_poc_script_from_dict(data)

    def _parse_poc_script_from_dict(self, data: dict | None) -> PoCScript | None:
        """Parse dict into PoCScript."""
        if not data or not data.get("script_content"):
            return None

        return PoCScript(
            language=data.get("language", "python"),
            script_content=data.get("script_content", ""),
            curl_command=data.get("curl_command", ""),
            browser_steps=data.get("browser_steps", []),
            expected_output=data.get("expected_output", ""),
            dependencies=data.get("dependencies", []),
        )

    # ── NEW: Hunter-Mode Intelligence Methods ────────────────────

    async def craft_targeted_payloads(
        self,
        endpoint: str,
        vuln_type: str,
        parameters: list[str],
        tech_stack: list[str],
        waf: str = "",
        previous_results: list[dict] | None = None,
    ) -> list[dict]:
        """
        LLM generates targeted payloads for a specific endpoint+vuln combo.
        Uses payload_generator under the hood with intelligence context.
        """
        from src.tools.exploit.payload_generator import generate_payloads

        context = {
            "url": endpoint,
            "parameter": parameters[0] if parameters else "",
            "method": "GET",
            "tech_stack": tech_stack,
            "waf": waf,
            "previous_responses": previous_results or [],
        }

        return await generate_payloads(
            brain_engine=self.brain,
            vuln_type=vuln_type,
            target_context=context,
            count=8,
        )

    async def write_custom_nuclei_templates(
        self,
        endpoints: list[dict],
        tech_stack: list[str],
        max_templates: int = 5,
    ) -> list[tuple[str, str]]:
        """
        LLM generates custom nuclei YAML templates for high-value endpoints.
        Returns list of (filename, yaml_content) tuples.
        """
        from src.tools.scanners.nuclei_template_writer import generate_targeted_templates

        return await generate_targeted_templates(
            brain_engine=self.brain,
            endpoints=endpoints,
            tech_stack=tech_stack,
            max_templates=max_templates,
        )

    async def run_deep_probe(
        self,
        targets: list[dict],
        session_dir: str = "",
        max_per_target: int = 4,
        oob_domain: str = "",
        interactsh: Any = None,
        auth_headers: dict[str, str] | None = None,
        host_profiles: dict[str, dict] | None = None,
    ) -> list[dict]:
        """
        Run LLM-driven deep probing on attack vectors.
        Returns Finding-compatible dicts for integration into raw_findings.
        """
        from src.workflow.pipelines.deep_probe import (
            deep_probe_batch,
            probe_sessions_to_findings,
        )

        sessions = await deep_probe_batch(
            targets=targets,
            brain_engine=self.brain,
            max_per_target=max_per_target,
            session_dir=session_dir,
            oob_domain=oob_domain,
            interactsh=interactsh,
            auth_headers=auth_headers,
            host_profiles=host_profiles,
        )

        return probe_sessions_to_findings(sessions)

    async def execute_and_verify_poc(
        self,
        finding: dict,
        poc_code: str,
        session_dir: str = "",
    ) -> dict:
        """
        Execute a PoC with iterative LLM refinement and return enhanced finding.
        """
        from src.tools.exploit.poc_executor import run_poc_with_refinement

        result = await run_poc_with_refinement(
            finding=finding,
            poc_code=poc_code,
            brain_engine=self.brain,
            max_iterations=3,
            timeout=1800.0,
            session_dir=session_dir,
        )

        return {
            "poc_status": result.status.value,
            "poc_confirmed": result.vulnerability_confirmed,
            "poc_evidence": result.evidence,
            "poc_confidence_boost": result.confidence_boost,
            "poc_iterations": result.iteration,
            "poc_output": result.raw_output[:3000],
        }

    async def generate_and_execute_poc(
        self,
        finding: dict,
        session_dir: str = "",
    ) -> dict:
        """
        Full pipeline: Generate PoC with LLM → Execute → Refine → Return result.
        This is the key method that PROVES vulnerabilities.
        """
        from src.tools.exploit.payload_generator import generate_poc_script
        from src.tools.exploit.poc_executor import run_poc_with_refinement

        # Step 1: Generate PoC
        poc_code = await generate_poc_script(
            brain_engine=self.brain,
            finding=finding,
        )

        if not poc_code:
            # Try curl PoC from existing finding data
            curl = finding.get("poc_curl", finding.get("curl_command", ""))
            if curl:
                poc_code = curl
            else:
                # B4: Fallback to template-based PoC before giving up
                try:
                    from src.tools.exploit.payload_generator import _generate_simple_poc
                    template_poc = _generate_simple_poc(finding)
                    if template_poc:
                        poc_code = template_poc
                        logger.info(f"Using template PoC fallback for {finding.get('title', '')[:50]}")
                    else:
                        return {
                            "poc_status": "generation_failed",
                            "poc_confirmed": False,
                            "poc_evidence": [],
                            "poc_confidence_boost": 0.0,
                        }
                except Exception as _exc:
                    return {
                        "poc_status": "generation_failed",
                        "poc_confirmed": False,
                        "poc_evidence": [],
                        "poc_confidence_boost": 0.0,
                    }

        # Step 2: Execute with refinement
        result = await run_poc_with_refinement(
            finding=finding,
            poc_code=poc_code,
            brain_engine=self.brain,
            max_iterations=3,
            timeout=1800.0,
            session_dir=session_dir,
        )

        return {
            "poc_status": result.status.value,
            "poc_confirmed": result.vulnerability_confirmed,
            "poc_evidence": result.evidence,
            "poc_confidence_boost": result.confidence_boost,
            "poc_iterations": result.iteration,
            "poc_code": result.poc_code[:5000],
            "poc_output": result.raw_output[:3000],
        }

    def get_stats(self) -> dict:
        """Return intelligence engine statistics."""
        return {
            "total_calls": self._call_count,
            "total_time": round(self._total_time, 2),
            "avg_time": round(self._total_time / max(1, self._call_count), 2),
            "cache_hits": self._cache_hits,
            "cache_size": len(self._cache),
            "consecutive_failures": self._consecutive_failures,
            "brain_down": self._brain_down,
            "brain_available": self.is_available,
        }

    # ══════════════════════════════════════════════════════════
    #  Agentic Pipeline Convenience Methods
    # ══════════════════════════════════════════════════════════

    async def decide_stage(
        self,
        context_summary: str,
        available_stages: list[str],
    ) -> dict[str, Any]:
        """Ask the brain which workflow stage to enter next.

        Returns a dict with at least ``stage`` (str) and ``reasoning`` (str).
        Falls back to the first available stage when the brain is unavailable.
        """
        if not self.is_available:
            fallback = available_stages[0] if available_stages else "passive_recon"
            return {"stage": fallback, "reasoning": "brain unavailable — default order"}

        from src.brain.prompts.agent_prompts import build_stage_selection_prompt

        prompt = build_stage_selection_prompt(
            context_summary=context_summary,
            available_stages=available_stages,
        )

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are an expert offensive security strategist deciding "
                "which recon/scan stage is most productive next. Reply in JSON: "
                '{"stage": "<chosen_stage>", "reasoning": "<one_sentence>"}'
            ),
            brain=BrainType.SECONDARY,
            timeout=60.0,
            task_type="stage_select",
        )
        if data and isinstance(data, dict) and "stage" in data:
            return data
        fallback = available_stages[0] if available_stages else "passive_recon"
        return {"stage": fallback, "reasoning": "parse error — default order"}

    async def evaluate_tool_result(
        self,
        unit_id: str,
        observations: str,
        findings_summary: str,
        context_summary: str,
    ) -> dict[str, Any]:
        """Evaluate a ToolUnit's result: quality, next step, hypotheses.

        Returns a dict with ``quality`` (str: low/medium/high),
        ``insights`` (str), ``new_hypotheses`` (list[str]),
        ``suggested_next`` (str), ``confidence_delta`` (int).
        """
        if not self.is_available:
            return {
                "quality": "medium",
                "insights": observations[:200],
                "new_hypotheses": [],
                "suggested_next": "",
                "confidence_delta": 0,
            }

        from src.brain.prompts.agent_prompts import build_agent_evaluate_prompt

        prompt = build_agent_evaluate_prompt(
            unit_id=unit_id,
            observations=observations,
            findings=findings_summary,
            context=context_summary,
        )

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are evaluating a security tool's output. "
                "Reply in JSON with keys: quality (low/medium/high), "
                "insights (str), new_hypotheses (list[str]), "
                "suggested_next (str), confidence_delta (int -20..+20)."
            ),
            brain=BrainType.PRIMARY,
            timeout=90.0,
            task_type="agent_evaluate",
        )
        if data and isinstance(data, dict):
            return data
        return {
            "quality": "medium",
            "insights": observations[:200],
            "new_hypotheses": [],
            "suggested_next": "",
            "confidence_delta": 0,
        }

    async def plan_attack_chain(
        self,
        findings: list[dict[str, Any]],
        technologies: list[str],
        context_summary: str,
    ) -> dict[str, Any]:
        """Plan a multi-step attack chain from existing findings.

        Returns a dict with ``chain_name`` (str), ``steps`` (list[dict]),
        ``expected_impact`` (str), ``confidence`` (float 0-1).
        """
        if not self.is_available:
            return {"chain_name": "", "steps": [], "expected_impact": "", "confidence": 0.0}

        from src.brain.prompts.agent_prompts import build_chain_attack_prompt

        prompt = build_chain_attack_prompt(
            findings=findings,
            technologies=technologies,
            context=context_summary,
        )

        data = await self._brain_call_json(
            prompt,
            system_prompt=(
                "You are planning an attack chain combining multiple low/medium "
                "findings into a high-impact exploit path. Think like a senior "
                "penetration tester. Reply in JSON with keys: chain_name (str), "
                "steps (list of {action, target, tool_or_technique}), "
                "expected_impact (str), confidence (float 0.0-1.0)."
            ),
            brain=BrainType.PRIMARY,
            timeout=120.0,
            task_type="chain_attack",
        )
        if data and isinstance(data, dict):
            return data
        return {"chain_name": "", "steps": [], "expected_impact": "", "confidence": 0.0}
