"""
WhiteHatHacker AI — WAF Artifact Patterns

WAF/CDN'lerin ürettiği sahte pozitif (false positive) pattern'leri.
Bu kalıplar, bir WAF'ın gerçek zafiyet olmayan durumlarda
ürettiği yanıtları tanımlar.
"""

from __future__ import annotations

from typing import Any

from loguru import logger


# ============================================================
# WAF Parmak İzleri
# ============================================================

WAF_FINGERPRINTS: dict[str, dict[str, Any]] = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cflb", "cf-request-id"],
        "cookies": ["__cflb", "__cf_bm", "cf_clearance"],
        "body_patterns": [
            "cloudflare",
            "ray id:",
            "performance & security by cloudflare",
            "enable javascript and cookies to continue",
        ],
        "status_codes": [403, 503, 1020],
        "block_indicators": [
            "attention required! | cloudflare",
            "error 1020",
            "access denied",
            "sorry, you have been blocked",
        ],
        "fp_impact": {
            # WAF block'u gerçek zafiyet sanılabilir
            "403_on_payload": -15,    # 403 dönmesi payload çalıştı değil, WAF block
            "challenge_page": -20,    # JS challenge sayfası
            "rate_limit": -10,        # Rate limiting
            "captcha": -18,           # CAPTCHA zorunluluğu
        },
    },
    "akamai": {
        "headers": [
            "x-akamai-transformed", "x-akamai-session-info",
            "akamai-origin-hop", "x-akamai-request-id",
        ],
        "cookies": ["akamai_generated", "bm_sv", "bm_sz"],
        "body_patterns": [
            "access denied",
            "reference#",
            "your request was identified as a potential threat",
        ],
        "status_codes": [403],
        "block_indicators": [
            "reference #",
            "access denied",
        ],
        "fp_impact": {
            "403_on_payload": -15,
            "reference_id_block": -18,
        },
    },
    "aws_waf": {
        "headers": [
            "x-amzn-requestid", "x-amz-cf-id", "x-amz-cf-pop",
        ],
        "cookies": ["awsalb", "awsalbcors"],
        "body_patterns": [
            "request blocked",
            "automated requests",
        ],
        "status_codes": [403, 429],
        "block_indicators": [
            "request blocked",
            "the request is blocked",
        ],
        "fp_impact": {
            "403_on_payload": -12,
            "rate_limit_429": -10,
        },
    },
    "imperva_incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
        "body_patterns": [
            "incapsula incident id",
            "powered by incapsula",
            "request unsuccessful",
        ],
        "status_codes": [403],
        "block_indicators": [
            "incapsula incident id",
            "request unsuccessful. incapsula",
        ],
        "fp_impact": {
            "403_on_payload": -15,
            "incident_page": -20,
        },
    },
    "f5_big_ip": {
        "headers": ["x-wa-info", "x-cnection"],
        "cookies": ["bigipserver", "bigipserverintranet", "ts_", "f5_"],
        "body_patterns": [
            "the requested url was rejected",
            "please consult with your administrator",
        ],
        "status_codes": [403],
        "block_indicators": [
            "the requested url was rejected",
        ],
        "fp_impact": {
            "403_on_payload": -12,
        },
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache", "server: sucuri"],
        "cookies": ["sucuri_cloudproxy_uuid"],
        "body_patterns": [
            "sucuri website firewall",
            "access denied - sucuri",
            "your request was blocked",
        ],
        "status_codes": [403],
        "block_indicators": [
            "access denied - sucuri",
            "sucuri website firewall",
        ],
        "fp_impact": {
            "403_on_payload": -15,
            "firewall_block": -18,
        },
    },
    "modsecurity": {
        "headers": ["server: modsecurity"],
        "cookies": [],
        "body_patterns": [
            "mod_security",
            "modsecurity",
            "not acceptable",
            "method not allowed",
        ],
        "status_codes": [403, 406],
        "block_indicators": [
            "mod_security",
            "modsecurity",
        ],
        "fp_impact": {
            "403_on_payload": -12,
            "406_not_acceptable": -15,
        },
    },
    "wordfence": {
        "headers": [],
        "cookies": ["wfwaf-authcookie"],
        "body_patterns": [
            "generated by wordfence",
            "a potentially unsafe operation has been detected",
            "your access to this site has been limited",
        ],
        "status_codes": [403, 503],
        "block_indicators": [
            "generated by wordfence",
            "your access to this site has been limited",
        ],
        "fp_impact": {
            "403_on_payload": -15,
            "wordfence_block": -18,
        },
    },
    "barracuda": {
        "headers": ["barra_counter_session"],
        "cookies": ["barra_counter_session", "bni__barracuda_lb_cookie"],
        "body_patterns": [
            "barracuda",
            "you are not authorized",
        ],
        "status_codes": [403],
        "block_indicators": [],
        "fp_impact": {
            "403_on_payload": -12,
        },
    },
}


# ============================================================
# CDN Parmak İzleri
# ============================================================

CDN_FINGERPRINTS: dict[str, dict[str, Any]] = {
    "cloudflare_cdn": {
        "headers": ["cf-cache-status", "cf-ray"],
        "fp_notes": "Cached responses may not reflect actual server behavior",
        "penalty": -3,
    },
    "fastly": {
        "headers": ["x-served-by", "x-cache", "x-cache-hits", "x-fastly-request-id"],
        "fp_notes": "Fastly CDN caching may alter responses",
        "penalty": -3,
    },
    "aws_cloudfront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "x-cache"],
        "fp_notes": "CloudFront may serve stale/cached content",
        "penalty": -3,
    },
    "akamai_cdn": {
        "headers": ["x-akamai-transformed"],
        "fp_notes": "Akamai may transform response content",
        "penalty": -4,
    },
    "varnish": {
        "headers": ["x-varnish", "via: varnish"],
        "fp_notes": "Varnish caching proxy",
        "penalty": -2,
    },
}


# ============================================================
# WAF Block vs Real Vuln Ayrımı
# ============================================================

# WAF block page'lerinin ortak özellikleri
WAF_BLOCK_PAGE_INDICATORS = [
    # Genel blok mesajları
    "access denied",
    "request blocked",
    "forbidden",
    "you have been blocked",
    "suspicious activity",
    "automated request detected",
    "your request was rejected",
    "security challenge",
    "enable javascript",
    "please complete the security check",
    "verify you are human",
    "captcha",
    "challenge-platform",
    # Specific WAF identifiers
    "reference id:",
    "incident id:",
    "ray id:",
    "request id:",
    "support id:",
    # WAF vendor strings
    "powered by",
    "web application firewall",
    "waf",
]


class WafArtifactDetector:
    """
    WAF/CDN artifact tespit motoru.

    Bir HTTP yanıtının WAF/CDN tarafından üretilip üretilmediğini
    tespit eder ve false positive etkisini hesaplar.

    Kullanım:
        detector = WafArtifactDetector()
        result = detector.analyze(
            response_headers={"cf-ray": "abc123", ...},
            response_body="Access denied...",
            status_code=403,
        )

        if result["waf_detected"]:
            confidence -= result["total_penalty"]
    """

    def analyze(
        self,
        response_headers: dict[str, str] | None = None,
        response_body: str = "",
        status_code: int = 200,
        cookies: dict[str, str] | None = None,
    ) -> dict[str, Any]:
        """
        Yanıtı WAF/CDN artifact'ler için analiz et.

        Returns:
            {
                "waf_detected": bool,
                "waf_name": str,
                "cdn_detected": bool,
                "cdn_name": str,
                "is_block_page": bool,
                "total_penalty": float,
                "details": list[str],
            }
        """
        result = {
            "waf_detected": False,
            "waf_name": "",
            "cdn_detected": False,
            "cdn_name": "",
            "is_block_page": False,
            "total_penalty": 0.0,
            "details": [],
        }

        headers = response_headers or {}
        header_lower = {k.lower(): v.lower() for k, v in headers.items()}
        body_lower = response_body.lower()[:5000]
        cookie_str = " ".join(f"{k}={v}" for k, v in (cookies or {}).items()).lower()

        # ── WAF Detection ──
        for waf_name, waf_info in WAF_FINGERPRINTS.items():
            detected = False

            # Header match
            for h in waf_info.get("headers", []):
                if h.lower() in header_lower or any(h.lower() in v for v in header_lower.values()):
                    detected = True
                    break

            # Cookie match
            if not detected:
                for c in waf_info.get("cookies", []):
                    if c.lower() in cookie_str:
                        detected = True
                        break

            # Body match
            if not detected:
                for pattern in waf_info.get("body_patterns", []):
                    if pattern.lower() in body_lower:
                        detected = True
                        break

            if detected:
                result["waf_detected"] = True
                result["waf_name"] = waf_name
                result["details"].append(f"WAF detected: {waf_name}")

                # Block page analizi
                block_indicators = waf_info.get("block_indicators", [])
                for indicator in block_indicators:
                    if indicator.lower() in body_lower:
                        result["is_block_page"] = True
                        result["details"].append(f"WAF block page detected: {indicator[:50]}")
                        break

                # Status code bazlı penalty
                fp_impact = waf_info.get("fp_impact", {})
                if status_code == 403:
                    penalty = fp_impact.get("403_on_payload", -12)
                    result["total_penalty"] += penalty
                    result["details"].append(f"403 with WAF → penalty={penalty}")
                elif status_code == 429:
                    penalty = fp_impact.get("rate_limit_429", -10) if "rate_limit_429" in fp_impact else fp_impact.get("rate_limit", -8)
                    result["total_penalty"] += penalty

                # Block page ek penalty
                if result["is_block_page"]:
                    extra = fp_impact.get("challenge_page", -5)
                    result["total_penalty"] += extra

                break  # İlk eşleşen WAF yeterli

        # ── CDN Detection ──
        for cdn_name, cdn_info in CDN_FINGERPRINTS.items():
            for h in cdn_info.get("headers", []):
                if h.lower() in header_lower:
                    result["cdn_detected"] = True
                    result["cdn_name"] = cdn_name
                    result["total_penalty"] += cdn_info.get("penalty", -3)
                    result["details"].append(f"CDN detected: {cdn_name}")
                    break
            if result["cdn_detected"]:
                break

        # ── Generic block page check ──
        if not result["is_block_page"] and status_code in (403, 406, 429, 503):
            block_matches = sum(
                1 for indicator in WAF_BLOCK_PAGE_INDICATORS
                if indicator.lower() in body_lower
            )
            if block_matches >= 2:
                result["is_block_page"] = True
                if not result["waf_detected"]:
                    result["waf_detected"] = True
                    result["waf_name"] = "unknown_waf"
                    result["total_penalty"] += -10
                    result["details"].append(f"Unknown WAF block page (matched {block_matches} indicators)")

        if result["waf_detected"]:
            logger.debug(
                f"WAF artifact analysis | waf={result['waf_name']} | "
                f"block={result['is_block_page']} | penalty={result['total_penalty']}"
            )

        return result


__all__ = [
    "WafArtifactDetector",
    "WAF_FINGERPRINTS",
    "CDN_FINGERPRINTS",
    "WAF_BLOCK_PAGE_INDICATORS",
]
